# Generated by Django 3.2 on 2024-02-28 16:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(default=1, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100)),
                ('title_description', models.TextField(blank=True, max_length=200)),
                ('genre', models.TextField(blank=True, max_length=50)),
                ('classification', models.TextField(blank=True, max_length=50)),
                ('background', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ChatItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_history', models.JSONField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('story_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.story')),
            ],
        ),
    ]
