# Generated by Django 3.2 on 2024-02-18 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatitem',
            name='background',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chatitem',
            name='classification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chatitem',
            name='create_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chatitem',
            name='genre',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chatitem',
            name='chat_history',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatitem',
            name='title_description',
            field=models.TextField(blank=True),
        ),
    ]
