# Generated by Django 3.2 on 2024-03-17 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_story_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charactor',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('personality', models.TextField(blank=True, max_length=1000)),
                ('story_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.story')),
            ],
        ),
    ]
