# Generated by Django 3.2 on 2024-03-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_charactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactor',
            name='greeting',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
