# Generated by Django 3.2 on 2024-03-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_charactor_greeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactor',
            name='original',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='story',
            name='official',
            field=models.BooleanField(default=False),
        ),
    ]
